# Generated by Django 5.2.5 on 2025-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='returnItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=15)),
                ('item_description', models.CharField(max_length=15)),
                ('location_found', models.CharField(max_length=15)),
                ('date_found', models.CharField(max_length=15)),
                ('item_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
