# Generated by Django 5.2.5 on 2025-08-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findlyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitemmodel',
            name='item_image',
            field=models.ImageField(default='fallback.jpg', upload_to='items'),
        ),
    ]
