# Generated by Django 5.2.5 on 2025-08-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findlyapp', '0002_alter_returnitemmodel_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitemmodel',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approval'),
        ),
    ]
