# Generated by Django 5.2.5 on 2025-08-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findlyapp', '0003_returnitemmodel_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitemmodel',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='returnitemmodel',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='approval'),
        ),
    ]
