# Generated by Django 5.2.5 on 2025-08-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findlyapp', '0004_remove_returnitemmodel_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitemmodel',
            name='image_url',
            field=models.URLField(default='https://example.com/placeholder.jpg'),
            preserve_default=False,
        ),
    ]
