# Generated by Django 5.2.5 on 2025-08-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findlyapp', '0005_returnitemmodel_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitemmodel',
            name='image_url',
        ),
    ]
