# Generated by Django 5.2.5 on 2025-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findlyapp', '0006_remove_returnitemmodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitemmodel',
            name='item_image',
            field=models.ImageField(default='fallback.jpg', upload_to='media/'),
        ),
    ]
