# Generated by Django 5.2.5 on 2025-08-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findlyapp', '0007_alter_returnitemmodel_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitemmodel',
            name='item_image',
            field=models.ImageField(default='fallback.jpg', upload_to='items/'),
        ),
    ]
